### ISSUE TITLE
cpu 使用率很高, 手机发烫

### ISSUE THREAD

**Issue by JMVivue** [SherlockQi/HeavenMemoirs#1]
非常感谢作者
想把他作为一个app的模块去显示; 
但  cpu 使用率很高, 手机发烫; 
比较纠结

**Comment by SherlockQi** [comment]
是的. CPU这个锅苹果背一半,我背一大大大半.我这里也算是提供一个思路,你看看思路是怎样的,自己去实现具体的需求,这样比较好.如果有哪里不明白,可以联系我.我会尽力解答.
