### ISSUE TITLE
大佬, 请问 sncp 素材怎么做的呀?

### ISSUE THREAD

**Issue by HolmesZhao** [SherlockQi/HeavenMemoirs#4]
大佬, 请问 sncp 素材怎么做的呀?

**Comment by SherlockQi** [comment]
我用的是 xcode 自带的.
新建文件 -> Resource 里选择 SceneKit Particle System File ,有几种效果可以选择.

**Comment by HolmesZhao** [comment]
搜嘎, ~就那么几种可选择呀, 哈哈, 谢了~
